FROM quay.io/fedora/fedora-bootc:44

RUN dnf install -y \
        @kde-desktop \
        plasma-workspace-wayland \
        chromium \
        git \
        micro && \
    dnf clean all

RUN bootc container lint